"use client";
import { useEffect,useState } from "react";
import { Badge } from "./ui";
type Kind="tna"|"evidence"|"gaps"|"interventions"|"audit";
type ApiRow={id:string;title?:string;objective?:string;status?:string;type?:string;priority?:string;sourceReference?:string;dueDate?:string;gap?:number;action?:string;resourceType?:string};
type ApiResult={items?:ApiRow[];asOf?:string;integrity?:{valid?:boolean}};
const endpoints:Record<Kind,string>={tna:"/api/tna",evidence:"/api/evidence",gaps:"/api/gaps",interventions:"/api/interventions",audit:"/api/audit"};
const titles:Record<Kind,string>={tna:"Live TNA portfolio",evidence:"Live evidence records",gaps:"Live diagnosed gaps",interventions:"Live action register",audit:"Live audit ledger"};
export function BackendTruth({kind,recordId}:{kind:Kind;recordId?:string}){const[state,setState]=useState<"loading"|"ready"|"unauthorized"|"error">("loading");const[data,setData]=useState<ApiResult>({});useEffect(()=>{let active=true;fetch(endpoints[kind],{cache:"no-store"}).then(async response=>{if(!active)return;if(response.status===401||response.status===403){setState("unauthorized");return}if(!response.ok)throw new Error();setData(await response.json() as ApiResult);setState("ready")}).catch(()=>active&&setState("error"));return()=>{active=false}},[kind]);const rows=(data.items??[]).filter(row=>!recordId||row.id===recordId||kind!=="tna");return <section className="panel backend-truth" aria-live="polite"><div className="panel-header"><div><p className="eyebrow">Authoritative system record</p><h2>{titles[kind]}</h2></div>{state==="ready"&&<Badge tone="success">Connected</Badge>}</div>{state==="loading"&&<p className="muted">Loading authorized records…</p>}{state==="unauthorized"&&<p className="backend-message">Sign in with an authorized role to view live records.</p>}{state==="error"&&<p className="backend-message error">Live records could not be loaded. The decision workspace remains available without implying data is current.</p>}{state==="ready"&&rows.length===0&&<p className="backend-message">No authorized records are available in this scope.</p>}{state==="ready"&&rows.length>0&&<div className="backend-rows">{rows.slice(0,5).map(row=>{const detail=row.objective??([row.type,row.priority&&`Priority ${row.priority}`,row.dueDate&&`Due ${row.dueDate}`].filter(Boolean).join(" · ")||"Governed record");return <div key={row.id}><span><strong>{row.title??row.action??row.sourceReference??row.resourceType??row.id}</strong><small>{detail}</small></span><Badge tone={row.priority==="critical"?"danger":row.status==="active"||row.status==="verified"?"success":"neutral"}>{row.status??row.priority??row.type??"recorded"}</Badge></div>})}</div>}{state==="ready"&&<small className="as-of">As of {data.asOf?new Date(data.asOf).toLocaleString():"current request"}{kind==="audit"&&data.integrity?` · Chain ${data.integrity.valid===false?"requires review":"verified"}`:""}</small>}</section>}
